Cria formulario de nova proposta e salva no banco de dados.
guimer00/e_participe pull request #7
Opened 2019-03-20 00:26 UTC by Rdnevess

Criado formulário para criação de novos projetos;

Na tela inicial ao pressionar o botão flutuante de adicionar, abrirá uma nova janela, nela preencher o formulário e então pressionar o botão flutuante de salvar.

2019-03-20 00:39 UTC, glauberatanaka requested changes
ajustes

2019-03-20 00:39 UTC, glauberatanaka commented on lib/ui/adicionarProposta.dart
> +              print('ERRROOOOOO' + e);
Ajustar método then e catchErro
SnackBar não está funcinando

2019-03-20 00:39 UTC, glauberatanaka commented on lib/ui/adicionarProposta.dart
> +            (formatDate(DateTime.now(), [dd, '/', MM, '/', yyyy]).toString());
Arrumar formato do datetime

2019-03-25 21:44 UTC, Rdnevess commented on lib/ui/adicionarProposta.dart
> +              print('ERRROOOOOO' + e);
Métodos funcionando;
SnackBar funcionando também.

2019-03-25 21:45 UTC, Rdnevess commented on lib/ui/adicionarProposta.dart
> +            (formatDate(DateTime.now(), [dd, '/', MM, '/', yyyy]).toString());
Formato corrigido no mesmo dia, faltou apenas o aviso aqui!

2019-03-27 00:47 UTC, glauberatanaka approved these changes

2019-03-27 00:48 UTC, merged